// frontend/src/common/components/post-avatar.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import styled from 'styled-components';
import { boxShadow, darkGrey } from '../css';
import { AuthorExpand, ProfileImg } from './shared-styled-components';
import {
  italicMixin,
  metaContentMixin
} from './shared-styled-components-mixins';

const ListAvatar = styled.div`
  display: flex;
  align-items: center;
`;
const ListAvatarImg = styled(ProfileImg)`
  height: 40px;
  width: 40px;
  &:hover {
    cursor: pointer;
    box-shadow: ${boxShadow};
  }
`;
const ListAvatarContent = styled.div`
  display: flex;
  flex-direction: column;
`;
const ListAvatarContentRow = styled.div`
  ${metaContentMixin};
  min-height: 18px; // height of metaContentMixin line-height
`;
const ListAvatarContentRowItalic = styled(ListAvatarContentRow)`
  ${italicMixin};
`;
const ListAvatarContentRowDarker = styled(ListAvatarContentRow)`
  color: ${darkGrey};
`;

export default ({ post, className, showHandle }) => {
  const postIsPrivate = !post.get('published');
  return (
    <ListAvatar className={className}>
      {(post.get('userProfileIsPublic') || postIsPrivate) && (
        <Link to={`/@${post.get('username')}`}>
          <ListAvatarImg src={post.get('profilePictureUrl')} />
        </Link>
      )}
      <ListAvatarContent>
        {(post.get('userProfileIsPublic') || postIsPrivate) && (
          <ListAvatarContentRowDarker>
            {post.get('givenName')} {post.get('familyName')}
          </ListAvatarContentRowDarker>
        )}
        <ListAvatarContentRowItalic>
          {postIsPrivate ? post.get('updated') : post.get('published')}
        </ListAvatarContentRowItalic>
        {showHandle && (
          <ListAvatarContentRow>
            <AuthorExpand to={`/public/?username=${post.get('username')}`}>
              @{post.get('username')}
            </AuthorExpand>
          </ListAvatarContentRow>
        )}
      </ListAvatarContent>
    </ListAvatar>
  );
};

// sapper/src/post-components/post-avatar.svelte
<script>
  export let post;
  export let showHandle;
  export let postIsPrivate;

  import ProfileImg from '../user-components/profile-img.svelte';
  import AuthorExpand from '../user-components/author-expand.svelte';
</script>

<style>
  .list-avatar {
    display: flex;
    align-items: center;
  }

  .list-avatar-content {
    display: flex;
    flex-direction: column;
  }

  .list-avatar-content-row {
    min-height: 18px;
    font-family: var(--filbert-sans-serif);
  }

  .italic {
    font-family: var(--filbert-italic-serif), sans-serif;
    color: var(--text-color-secondary);
  }
</style>


<div class="list-avatar">
  {#if post.get('userProfileIsPublic') || postIsPrivate}
    <a href="/@{post.get('username')}">
      <ProfileImg src={post.get('profilePictureUrl')} height="40px" width="40px" shouldApplyHoverStyle />
    </a>
  {/if}
  <div class="list-avatar-content">
    {#if post.get('userProfileIsPublic') || postIsPrivate}
      <div><a class="filbert-link list-avatar-content-row" href="/@{post.get('username')}">
        {post.get('givenName')} {post.get('familyName')}
      </a></div>
    {/if}
    <div class="meta-font-mixin list-avatar-content-row italic">
      {postIsPrivate ? post.get('updated') : post.get('published')}
    </div>
    {#if showHandle}
      <div class="meta-font-mixin list-avatar-content-row">
        <AuthorExpand username={post.get('username')} />
      </div>
    {/if}
  </div>
</div>
