// frontend/src/pages/edit/format-selection-menu.jsx
import * as React from 'react';
import styled, { css } from 'styled-components';
import { blue, darkBlue, darkGrey } from '../../common/css';
import {
  SELECTION_ACTION_BOLD,
  SELECTION_ACTION_ITALIC,
  SELECTION_ACTION_CODE,
  SELECTION_ACTION_SITEINFO,
  SELECTION_ACTION_STRIKETHROUGH,
  SELECTION_ACTION_LINK,
  SELECTION_LINK_URL,
  SELECTION_ACTION_H1,
  SELECTION_ACTION_H2,
  NODE_TYPE_SECTION_H1,
  NODE_TYPE_SECTION_H2,
} from '../../common/constants';

import IconBoldSvg from '../../../assets/bold.svg';
import IconItalicSvg from '../../../assets/italic.svg';
import IconCodeSvg from '../../../assets/code.svg';
import IconInfoSvg from '../../../assets/info.svg';
import IconStrikethroughSvg from '../../../assets/strikethrough.svg';
import IconLinkSvg from '../../../assets/link.svg';
import IconH1Svg from '../../../assets/h1.svg';
import IconH2Svg from '../../../assets/h2.svg';

const SvgIconMixin = css`
  fill: #fff;
  position: relative;
  top: -1px;
  vertical-align: middle;
  height: 21px;
  &:hover {
    fill: ${blue};
  }
  ${p => p.selected && `
    fill: ${darkBlue};
  `}
`;
const IconBold = styled(IconBoldSvg)`
  ${SvgIconMixin};
`;
const IconItalic = styled(IconItalicSvg)`
  ${SvgIconMixin};
`;
const IconCode = styled(IconCodeSvg)`
  ${SvgIconMixin};
`;
const IconSiteinfo = styled(IconInfoSvg)`
  ${SvgIconMixin};
`;
const IconStrikethrough = styled(IconStrikethroughSvg)`
  ${SvgIconMixin};
`;
const IconLink = styled(IconLinkSvg)`
  ${SvgIconMixin};
`;
const IconH1 = styled(IconH1Svg)`
  ${SvgIconMixin};
`;
const IconH2 = styled(IconH2Svg)`
  ${SvgIconMixin};
`;

export const FormatSelectionMenu = styled.div`
  position: absolute;
  transition: .1s top;
  top: ${p => p.top - (p.shouldShowUrl ? 80 : 50)}px;
  left: ${p => p.left - 165}px; // 165 is half the width of the menu
  z-index: 11;
  background-image: linear-gradient(to bottom,rgba(49,49,47,.99),#262625);
  background-repeat: repeat-x;
  border-radius: 5px;
  padding: 0 10px;
  color: ${darkGrey};
`;
export const FormatButton = styled.button`
  position: relative;
  background: rgba(0,0,0,0);
  color: white;
  font-size: 16px;
  transition: .1s background-color,.1s border-color,.1s color,.1s fill;
  border: 0;
  display: inline-block;
  vertical-align: middle;
  height: 44px;
  line-height: 21px;
  margin: 0 8px;
  padding: 0;
  cursor: pointer;
  user-select: none;
  outline: 0;
`;
export const ButtonSeparator = styled.div`
  display: inline-block;
  vertical-align: middle;
  width: 1px;
  margin: 0 6px;
  height: 24px;
  background: rgba(255,255,255,.2);
`;
export const LinkInput = styled.input`
  background: rgba(0,0,0,0);
  display: block;
  height: 0;
  width: 100%;
  padding: 0;
  margin: 0;
  color: #fff;
  border: none;
  outline: 0;
  font-size: 16px;
  box-sizing: border-box;
  border-radius: 5px;
  appearance: none;
  transition: .05s height;
  ${p => p.selected && `
    padding: 12px;
    padding-top: 0;
    height: 30px;
  `}
`;
export const PointClip = styled.div`
  position: absolute;
  bottom: -10px;
  left: 50%;
  clip: rect(10px 20px 20px 0);
  margin-left: -10px;
`;
export const Arrow = styled.span`
  display: block;
  width: 20px;
  height: 20px;
  background-color: #262625;
  transform: rotate(45deg) scale(.5);
`;

export default ({
                  offsetTop,
                  offsetLeft,
                  nodeModel,
                  selectionModel,
                  selectionAction,
                  updateLinkUrl,
                }) => (
  <FormatSelectionMenu shouldShowUrl={selectionModel.get(SELECTION_ACTION_LINK)} top={offsetTop} left={offsetLeft}>
    <FormatButton onClick={() => selectionAction(SELECTION_ACTION_BOLD)}>
      <IconBold selected={selectionModel.get(SELECTION_ACTION_BOLD)} />
    </FormatButton>
    <FormatButton onClick={() => selectionAction(SELECTION_ACTION_ITALIC)}>
      <IconItalic selected={selectionModel.get(SELECTION_ACTION_ITALIC)} />
    </FormatButton>
    <FormatButton onClick={() => selectionAction(SELECTION_ACTION_CODE)}>
      <IconCode selected={selectionModel.get(SELECTION_ACTION_CODE)} />
    </FormatButton>
    <FormatButton onClick={() => selectionAction(SELECTION_ACTION_SITEINFO)}>
      <IconSiteinfo selected={selectionModel.get(SELECTION_ACTION_SITEINFO)} />
    </FormatButton>
    <FormatButton onClick={() => selectionAction(SELECTION_ACTION_STRIKETHROUGH)}>
      <IconStrikethrough selected={selectionModel.get(SELECTION_ACTION_STRIKETHROUGH)} />
    </FormatButton>
    <FormatButton onClick={() => selectionAction(SELECTION_ACTION_LINK)}>
      <IconLink selected={selectionModel.get(SELECTION_ACTION_LINK)} />
    </FormatButton>
    <ButtonSeparator />
    <FormatButton onClick={() => selectionAction(SELECTION_ACTION_H1)}>
      <IconH1 selected={nodeModel.get('type') === NODE_TYPE_SECTION_H1} />
    </FormatButton>
    <FormatButton onClick={() => selectionAction(SELECTION_ACTION_H2)}>
      <IconH2 selected={nodeModel.get('type') === NODE_TYPE_SECTION_H2} />
    </FormatButton>
    <LinkInput
      placeholder="Enter URL here..."
      selected={selectionModel.get(SELECTION_ACTION_LINK)}
      onChange={(e) => updateLinkUrl(e.target.value)}
      value={selectionModel.get(SELECTION_LINK_URL)}
    />
    <PointClip>
      <Arrow />
    </PointClip>
  </FormatSelectionMenu>
)

// web/src/editor-components/FormatSelectionMenu.svelte
<script>
  export let nodeModel = Map();
  export let selectionModel = Map();
  export let selectionAction;
  export let offsetTop;
  export let offsetLeft;
  export let updateLinkUrl;
  export let closeMenu;

  import { Map } from 'immutable';
  import { beforeUpdate, onMount } from 'svelte';

  import {
    SELECTION_ACTION_LINK,
    SELECTION_LINK_URL,
    SELECTION_ACTION_BOLD,
    SELECTION_ACTION_ITALIC,
    SELECTION_ACTION_CODE,
    SELECTION_ACTION_SITEINFO,
    SELECTION_ACTION_MINI,
    SELECTION_ACTION_STRIKETHROUGH,
    SELECTION_ACTION_H1,
    SELECTION_ACTION_H2,
    NODE_TYPE_H1,
    NODE_TYPE_H2,
  } from '../common/constants';

  import { stopAndPrevent } from '../common/utils';

  import Cursor from '../form-components/Cursor.svelte';
  import IconButton from '../form-components/IconButton.svelte';
  import IconBold from '../icons/bold.svelte';
  import IconItalic from '../icons/italic.svelte';
  import IconCode from '../icons/code.svelte';
  import IconSiteinfo from '../icons/info.svelte';
  import IconStrikethrough from '../icons/strikethrough.svelte';
  import IconLink from '../icons/link.svelte';
  import IconH1 from '../icons/h1.svelte';
  import IconH2 from '../icons/h2.svelte';
  import IconMini from '../icons/mini.svelte';

  $: boldIsEnabled = selectionModel.get(SELECTION_ACTION_BOLD);
  $: italicIsEnabled = selectionModel.get(SELECTION_ACTION_ITALIC);
  $: codeIsEnabled = selectionModel.get(SELECTION_ACTION_CODE);
  $: siteinfoIsEnabled = selectionModel.get(SELECTION_ACTION_SITEINFO);
  $: miniIsEnabled = selectionModel.get(SELECTION_ACTION_MINI);
  $: strikethroughIsEnabled = selectionModel.get(
    SELECTION_ACTION_STRIKETHROUGH
  );
  $: linkIsEnabled = selectionModel.get(SELECTION_ACTION_LINK);
  $: h1IsEnabled = nodeModel.get('type') === NODE_TYPE_H1;
  $: h2IsEnabled = nodeModel.get('type') === NODE_TYPE_H2;

  let formatSelectionMenuDomNode;
  let linkUrlInputDomNode;
  let isMenuOpen = true;
  const linkMenuItemIdx = 6;
  let currentIdx = selectionModel.get(SELECTION_ACTION_LINK)
    ? linkMenuItemIdx
    : -1;

  beforeUpdate(() => {
    if (formatSelectionMenuDomNode) {
      // 44 is the height of menu, 10 is the height of arrow point
      formatSelectionMenuDomNode.style.top = `${
        offsetTop - 120 - (selectionModel.get(SELECTION_ACTION_LINK) ? 30 : 0)
      }px`;
      // 203 is half the width of the menu
      formatSelectionMenuDomNode.style.left = `${offsetLeft - 203}px`;
    }
  });

  function handleKeyDown(evt) {}

  onMount(() => {
    // `capture: true` AKA "capture phase" will put this event handler in front of the ones set by edit.jsx
    window.addEventListener('keydown', handleKeyDown, { capture: true });
    // override top level mouseup handler
    function noop(e) {
      if (formatSelectionMenuDomNode.contains(e.target)) {
        stopAndPrevent(e);
      }
    }
    window.addEventListener('mouseup', noop, { capture: true });

    return () => {
      window.removeEventListener('keydown', handleKeyDown, {
        capture: true,
      });
      window.removeEventListener('mouseup', noop, {
        capture: true,
      });
    };
  });

  function isFormatEnabled(type) {
    if (
      nodeModel.get('type') === NODE_TYPE_H1 &&
      type === SELECTION_ACTION_H1
    ) {
      return true;
    }
    if (
      nodeModel.get('type') === NODE_TYPE_H2 &&
      type === SELECTION_ACTION_H2
    ) {
      return true;
    }
    return selectionModel.get(type) || undefined;
  }
</script>

<style>
  #format-selection-menu {
    display: none;
  }
  #format-selection-menu.open {
    display: block;
  }
  .svg-container {
    height: 21px;
    width: 21px;
    margin-bottom: 4px;
  }
  .button-separator {
    display: inline-block;
    vertical-align: middle;
    width: 1px;
    margin: 0 6px;
    height: 24px;
    background: rgba(255, 255, 255, 0.2);
  }
  input {
    height: 0;
    padding: 0;
    transition: 0.05s height;
  }
  input.enabled {
    padding: 0 12px 12px;
    height: 30px;
  }
</style>

<div
  id="format-selection-menu"
  class="lil-sassy-menu"
  data-is-menu
  bind:this="{formatSelectionMenuDomNode}"
  class:open="{isMenuOpen}"
>
  <IconButton
    id="{`format-selection-menu-${SELECTION_ACTION_BOLD}`}"
    on:click="{() => selectionAction(SELECTION_ACTION_BOLD)}"
  >
    <div class="svg-container">
      <IconBold useIconMixin selected="{boldIsEnabled}" />
    </div>
    {#if currentIdx === 0}
      <Cursor />
    {/if}
  </IconButton>
  <IconButton
    id="{`format-selection-menu-${SELECTION_ACTION_ITALIC}`}"
    on:click="{() => selectionAction(SELECTION_ACTION_ITALIC)}"
  >
    <div class="svg-container">
      <IconItalic useIconMixin selected="{italicIsEnabled}" />
    </div>
    {#if currentIdx === 1}
      <Cursor />
    {/if}
  </IconButton>
  <IconButton
    id="{`format-selection-menu-${SELECTION_ACTION_CODE}`}"
    on:click="{() => selectionAction(SELECTION_ACTION_CODE)}"
  >
    <div class="svg-container">
      <IconCode useIconMixin selected="{codeIsEnabled}" />
    </div>
    {#if currentIdx === 2}
      <Cursor />
    {/if}
  </IconButton>
  <IconButton
    id="{`format-selection-menu-${SELECTION_ACTION_SITEINFO}`}"
    on:click="{() => selectionAction(SELECTION_ACTION_SITEINFO)}"
  >
    <div class="svg-container">
      <IconSiteinfo useIconMixin selected="{siteinfoIsEnabled}" />
    </div>
    {#if currentIdx === 3}
      <Cursor />
    {/if}
  </IconButton>
  <IconButton
    id="{`format-selection-menu-${SELECTION_ACTION_MINI}`}"
    on:click="{() => selectionAction(SELECTION_ACTION_MINI)}"
  >
    <div class="svg-container">
      <IconMini useIconMixin selected="{miniIsEnabled}" />
    </div>
    {#if currentIdx === 4}
      <Cursor />
    {/if}
  </IconButton>
  <IconButton
    id="{`format-selection-menu-${SELECTION_ACTION_STRIKETHROUGH}`}"
    on:click="{() => selectionAction(SELECTION_ACTION_STRIKETHROUGH)}"
  >
    <div class="svg-container">
      <IconStrikethrough useIconMixin selected="{strikethroughIsEnabled}" />
    </div>
    {#if currentIdx === 5}
      <Cursor />
    {/if}
  </IconButton>
  <IconButton
    id="{`format-selection-menu-${SELECTION_ACTION_LINK}`}"
    on:click="{() => selectionAction(SELECTION_ACTION_LINK)}"
  >
    <div class="svg-container">
      <IconLink useIconMixin selected="{linkIsEnabled}" />
    </div>
    {#if currentIdx === 6}
      <Cursor />
    {/if}
  </IconButton>
  <div class="button-separator"></div>
  <IconButton
    id="{`format-selection-menu-${SELECTION_ACTION_H1}`}"
    on:click="{() => selectionAction(SELECTION_ACTION_H1)}"
  >
    <div class="svg-container">
      <IconH1 useIconMixin selected="{h1IsEnabled}" />
    </div>
    {#if currentIdx === 7}
      <Cursor />
    {/if}
  </IconButton>
  <IconButton
    id="{`format-selection-menu-${SELECTION_ACTION_H2}`}"
    on:click="{() => selectionAction(SELECTION_ACTION_H2)}"
  >
    <div class="svg-container">
      <IconH2 useIconMixin selected="{h2IsEnabled}" />
    </div>
    {#if currentIdx === 8}
      <Cursor />
    {/if}
  </IconButton>
  <input
    id="format-selection-menu-link-url-input"
    class="dark-input"
    placeholder="Enter URL here..."
    bind:this="{linkUrlInputDomNode}"
    class:enabled="{selectionModel.get(SELECTION_ACTION_LINK)}"
    on:input="{(e) => updateLinkUrl(e.target.value)}"
    value="{selectionModel.get(SELECTION_LINK_URL, '')}"
  />
  <div class="point-clip">
    <div class="arrow"></div>
  </div>
</div>
