// web/src/document-components/Document.svelte
<script>
  export let nodesById = Map();
  export let currentEditNode = Map();
  export let setEditNodeId = undefined;

  import { Map } from 'immutable';
  import {
    NODE_TYPE_H1,
    NODE_TYPE_H2,
    NODE_TYPE_IMAGE,
    NODE_TYPE_LI,
    NODE_TYPE_P,
    NODE_TYPE_PRE,
    NODE_TYPE_QUOTE,
    NODE_TYPE_ROOT,
    NODE_TYPE_SPACER,
    NODE_TYPE_CONTENT,
    NODE_TYPE_CODE,
    NODE_TYPE_OL,
  } from '../common/constants';
  import { cleanText, getFirstNode } from '../common/utils';
  import H1 from './H1.svelte';
  import H2 from './H2.svelte';
  import Li from './Li.svelte';
  import P from './P.svelte';
  import Pre from './Pre.svelte';
  import Spacer from './Spacer.svelte';
  import Image from './Image.svelte';
  import Quote from './Quote.svelte';

  let current;
  let nodesInOrder;

  function next() {
    current = nodesById.get(current.get('next_sibling_id')) || Map();
  }

  function getParagraphs() {
    if (current.get('type') !== NODE_TYPE_P) {
      return null;
    }
    const paragraphs = [];
    while (current.get('type') === NODE_TYPE_P) {
      paragraphs.push(current);
      next();
    }
    return paragraphs;
  }

  function getOrderedList() {
    if (current.get('type') !== NODE_TYPE_LI) {
      return null;
    }
    const listItems = [];
    while (current.get('type') === NODE_TYPE_LI) {
      listItems.push(current);
      next();
    }
    return listItems;
  }

  function getContentSection() {
    const contentNodes = [];
    let p;
    let li;
    do {
      p = getParagraphs();
      li = getOrderedList();
      if (p) {
        contentNodes.push(...p);
      }
      if (li) {
        contentNodes.push(li);
      }
    } while (p || li);
    return { type: NODE_TYPE_CONTENT, nodes: contentNodes };
  }

  function getCodeSection() {
    const preNodes = [];
    while (current.get('type') === NODE_TYPE_PRE) {
      preNodes.push(current);
      next();
    }
    return { type: NODE_TYPE_CODE, nodes: preNodes };
  }

  $: {
    current = getFirstNode(nodesById);
    nodesInOrder = [];
    while (current.get('id')) {
      let shouldAdvanceCurrent = true;
      if ([NODE_TYPE_P, NODE_TYPE_LI].includes(current.get('type'))) {
        nodesInOrder.push(getContentSection());
        shouldAdvanceCurrent = false;
      } else if ([NODE_TYPE_PRE].includes(current.get('type'))) {
        nodesInOrder.push(getCodeSection());
        shouldAdvanceCurrent = false;
      } else {
        nodesInOrder.push(current);
      }
      if (shouldAdvanceCurrent) {
        next();
      }
    }
  }
</script>

<style>
  div {
    margin-bottom: 96px;
  }

  .code-section {
    margin-bottom: 52px;
    font-family: var(--code-font-family), monospace;
    font-size: 16px;
    font-weight: var(--code-font-weight);
    max-height: 350px;
    letter-spacing: var(--code-letter-spacing);
    word-spacing: -0.2em;
    line-height: var(--code-line-height);
    background: var(--background-color-secondary);
    padding: 20px;
    overflow: auto;
    counter-reset: code;
  }

  ol {
    margin-bottom: 38px;
    counter-reset: post;
    padding: 0;
    list-style: none none;
    word-break: break-word;
    visibility: visible;
  }
</style>

<div>
  {#each nodesInOrder as node}
    {#if !Map.isMap(node) && node.type === NODE_TYPE_CONTENT}
      <section class="filbert-section content-section">
        {#each node.nodes as nodeInner}
          {#if !Map.isMap(nodeInner)}
            <ol>
              {#each nodeInner as li}
                <Li node="{li}" />
              {/each}
            </ol>
          {:else}
            <P node="{nodeInner}" />
          {/if}
        {/each}
      </section>
    {:else if !Map.isMap(node) && node.type === NODE_TYPE_CODE}
      <section class="filbert-section code-section">
        {#each node.nodes as pre}
          <Pre node="{pre}" />
        {/each}
      </section>
    {:else if node.get('type') === NODE_TYPE_H1}
      <H1
        {node}
        shouldShowPlaceholder="{nodesById.size === 1 && cleanText(node.get('content', '')).length === 0}"
      />
    {:else if node.get('type') === NODE_TYPE_H2}
      <H2 {node} />
    {:else if node.get('type') === NODE_TYPE_SPACER}
      <Spacer
        {node}
        {setEditNodeId}
        isEditing="{node.get('id') === currentEditNode.get('id')}"
      />
    {:else if node.get('type') === NODE_TYPE_IMAGE}
      <Image
        {node}
        hideBorder="{false}"
        {setEditNodeId}
        isEditing="{node.get('id') === currentEditNode.get('id')}"
      />
    {:else if node.get('type') === NODE_TYPE_QUOTE}
      <Quote
        {node}
        {setEditNodeId}
        isEditing="{node.get('id') === currentEditNode.get('id')}"
      />
    {/if}
  {/each}
</div>

// frontend/src/common/components/document.component.jsx
import React from 'react';
import styled from 'styled-components';
import { Map } from 'immutable';
import {
  NODE_TYPE_H1,
  NODE_TYPE_H2,
  NODE_TYPE_IMAGE,
  NODE_TYPE_LI,
  NODE_TYPE_P,
  NODE_TYPE_PRE,
  NODE_TYPE_QUOTE,
  NODE_TYPE_ROOT,
  NODE_TYPE_SPACER
} from '../constants';
import { CodeSection, ContentSection, Ol } from './shared-styled-components';
import Quote from './quote';
import Image from './image';
import Spacer from './spacer';
import H2 from './h2';
import H1 from './h1';
import Pre from './pre';
import P from './p';
import Li from './li';
import { cleanText } from '../utils';
import DocumentModel from '../../pages/edit/document-model';

const Root = styled.div`
  margin-bottom: 96px;
`;

function getChildIds(children) {
  return children.reduce((acc, c) => `${acc}${c.key}`, '');
}

export default class Document extends React.PureComponent {
  current;

  getNextPTags() {
    if (this.current.get('type') !== NODE_TYPE_P) {
      return null;
    }
    const children = [];
    while (this.current.get('type') === NODE_TYPE_P) {
      children.push(<P key={this.current.get('id')} node={this.current} />);
      this.next();
    }
    return children;
  }

  getNextLiTags() {
    if (this.current.get('type') !== NODE_TYPE_LI) {
      return null;
    }
    const children = [];
    while (this.current.get('type') === NODE_TYPE_LI) {
      children.push(<Li key={this.current.get('id')} node={this.current} />);
      this.next();
    }
    return <Ol key={getChildIds(children)}>{children}</Ol>;
  }

  getContentSectionTags() {
    const children = [];
    let p;
    let li;
    do {
      p = this.getNextPTags();
      li = this.getNextLiTags();
      if (p) {
        children.push(...p);
      }
      if (li) {
        children.push(li);
      }
    } while (p || li);
    return (
      <ContentSection key={getChildIds(children)}>{children}</ContentSection>
    );
  }

  getNextPreTags() {
    const children = [];
    while (this.current.get('type') === NODE_TYPE_PRE) {
      children.push(<Pre key={this.current.get('id')} node={this.current} />);
      this.next();
    }
    return <CodeSection key={getChildIds(children)}>{children}</CodeSection>;
  }

  next = () => {
    this.current =
      this.props?.nodesById?.get?.(this.current.get('next_sibling_id')) ||
      Map();
  };

  render() {
    console.debug('Document RENDER', this);
    const {
      props: { nodesById, currentEditNode = Map(), setEditNodeId }
    } = this;
    const children = [];
    this.current = DocumentModel.getFirstNode(nodesById);
    while (this.current.get('id')) {
      let shouldCallNext = true;
      const currentType = this.current.get('type');
      if (currentType === NODE_TYPE_P || currentType === NODE_TYPE_LI) {
        children.push(this.getContentSectionTags());
        shouldCallNext = false; // next() already in correct position
      } else if (currentType === NODE_TYPE_PRE) {
        children.push(this.getNextPreTags());
        shouldCallNext = false; // next() already in correct position
      } else if (currentType === NODE_TYPE_H1) {
        children.push(
          <H1
            key={this.current.get('id')}
            node={this.current}
            shouldShowPlaceholder={
              nodesById.size === 1 &&
              cleanText(this.current.get('content', '')).length === 0
            }
          />
        );
      } else if (currentType === NODE_TYPE_H2) {
        children.push(<H2 key={this.current.get('id')} node={this.current} />);
      } else if (currentType === NODE_TYPE_SPACER) {
        children.push(
          <Spacer
            key={this.current.get('id')}
            node={this.current}
            isEditing={currentEditNode.get('id') === this.current.get('id')}
            setEditNodeId={setEditNodeId}
          />
        );
      } else if (currentType === NODE_TYPE_IMAGE) {
        children.push(
          <Image
            key={this.current.get('id')}
            node={this.current}
            isEditing={currentEditNode.get('id') === this.current.get('id')}
            setEditNodeId={setEditNodeId}
          />
        );
      } else if (currentType === NODE_TYPE_QUOTE) {
        children.push(
          <Quote
            key={this.current.get('id')}
            node={this.current}
            isEditing={currentEditNode.get('id') === this.current.get('id')}
            setEditNodeId={setEditNodeId}
          />
        );
      } else {
        console.error('Error: Unknown type! ', this.current.get('type'));
      }
      if (shouldCallNext) {
        this.next();
      }
    }
    return <Root data-type={NODE_TYPE_ROOT}>{children}</Root>;
  }
}

// these could be interesting in the editor 'add' menu but, they're currently supported with existing node types
// export const Gotcha = {} // facepalm emoji
// export const Tangent = {} // horse emoji
// export const Shrug = {} // shrug emoji
