// web/src/post-components/PostAvatar.svelte
<script>
  export let post;
  export let showHandle = false;

  $: postMap = Map(post);
  $: postIsPrivate = !postMap.get('published');

  import { Map } from 'immutable';
  import ProfileImg from '../user-components/ProfileImg.svelte';
  import ExpandLink from '../layout-components/ExpandLink.svelte';
</script>

<style>
  .list-avatar {
    display: flex;
    align-items: center;
  }

  .list-avatar-content {
    display: flex;
    flex-direction: column;
  }

  .list-avatar-content-row {
    min-height: 18px;
    font-family: var(--filbert-sans-serif);
  }

  .italic {
    font-family: var(--filbert-italic-serif), sans-serif;
    color: var(--text-color-secondary);
  }
</style>

<div class="list-avatar">
  {#if postMap.get('userProfileIsPublic') || postIsPrivate}
    <a href="/user/@{postMap.get('username')}">
      <ProfileImg
        src="{postMap.get('profilePictureUrl')}"
        height="40px"
        width="40px"
        shouldApplyHoverStyle
      />
    </a>
  {/if}
  <div class="list-avatar-content">
    {#if postMap.get('userProfileIsPublic') || postIsPrivate}
      <div>
        <a
          class="filbert-link list-avatar-content-row"
          href="/user/@{postMap.get('username')}"
        >
          {postMap.get('givenName')} {postMap.get('familyName')}
        </a>
      </div>
    {/if}
    <div class="meta-font list-avatar-content-row italic">
      {postIsPrivate ? postMap.get('updated') : postMap.get('published')}
    </div>
    {#if showHandle}
      <div class="meta-font list-avatar-content-row">
        <ExpandLink url="/public/?username={postMap.get('username')}">
          @{postMap.get('username')}
        </ExpandLink>
      </div>
    {/if}
  </div>
</div>

// frontend/src/common/components/post-avatar.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import styled from 'styled-components';
import { boxShadow, darkGrey } from '../css';
import { AuthorExpand, ProfileImg } from './shared-styled-components';
import {
  italicMixin,
  metaContentMixin
} from './shared-styled-components-mixins';

const ListAvatar = styled.div`
  display: flex;
  align-items: center;
`;
const ListAvatarImg = styled(ProfileImg)`
  height: 40px;
  width: 40px;
  &:hover {
    cursor: pointer;
    box-shadow: ${boxShadow};
  }
`;
const ListAvatarContent = styled.div`
  display: flex;
  flex-direction: column;
`;
const ListAvatarContentRow = styled.div`
  ${metaContentMixin};
  min-height: 18px; // height of metaContentMixin line-height
`;
const ListAvatarContentRowItalic = styled(ListAvatarContentRow)`
  ${italicMixin};
`;
const ListAvatarContentRowDarker = styled(ListAvatarContentRow)`
  color: ${darkGrey};
`;

export default ({ post, className, showHandle }) => {
  const postIsPrivate = !post.get('published');
  return (
    <ListAvatar className={className}>
      {(post.get('userProfileIsPublic') || postIsPrivate) && (
        <Link to={`/@${post.get('username')}`}>
          <ListAvatarImg src={post.get('profilePictureUrl')} />
        </Link>
      )}
      <ListAvatarContent>
        {(post.get('userProfileIsPublic') || postIsPrivate) && (
          <ListAvatarContentRowDarker>
            {post.get('givenName')} {post.get('familyName')}
          </ListAvatarContentRowDarker>
        )}
        <ListAvatarContentRowItalic>
          {postIsPrivate ? post.get('updated') : post.get('published')}
        </ListAvatarContentRowItalic>
        {showHandle && (
          <ListAvatarContentRow>
            <AuthorExpand to={`/public/?username=${post.get('username')}`}>
              @{post.get('username')}
            </AuthorExpand>
          </ListAvatarContentRow>
        )}
      </ListAvatarContent>
    </ListAvatar>
  );
};
