// sapper/src/post-components/PostListRow.svelte
<script>
  export let post;
  export let postIsPrivate = false;

  import {onMount} from 'svelte';

  import PostAvatar from './PostAvatar.svelte';
  import Image from '../document-components/Image.svelte';
  import AuthorExpand from '../user-components/AuthorExpand.svelte';

  let nextUrl;
  onMount(async () => {
    const { createNextUrl } = await import('../common/dom');
    nextUrl = createNextUrl(`/manage/${post.get('id')}`);
  })
</script>

<style>
  .abstract-link {
    max-height: 48px;
    font-size: 19px;
    line-height: 24px;
    color: var(--filbert-grey);
    letter-spacing: 0px;
  }

  .heading-link {
    max-height: 56px;
    letter-spacing: -0.5px;
    font-size: 25px;
    line-height: 28px;
    font-weight: 600;
  }

  .post-row {
    max-width: var(--filbert-viewport7);
    padding: 16px 0;
    border-top: 1px solid var(--background-color-secondary);
    align-items: center;
  }

  .post-row:last-of-type {
    margin-bottom: 42px;
  }

  .image-col {
    padding: 0;
    flex: 1;
    margin-bottom: 16px;
  }

  .details-col {
    padding: 0;
    flex: 4;
  }

  .post-abstract-row {
    margin-top: 4px;
  }

  .post-meta-row {
    display: flex;
    align-items: center;
    margin-top: 8px;
  }

  .post-action-container {
    position: relative;
    min-height: 18px;
    display: inline-block;
    padding-left: var(--padding-left, 8px);
  }

  .post-action-container:first-of-type {
    padding-left: 0;
  }

  .post-action-link {
    /* TODO: this is copied from .meta-font because of specificity issues */
    letter-spacing: 0px;
    font-size: 16px;
    line-height: 18px;
    font-style: normal;
    /* end */
    padding: 6px 8px;
  }

  @media (min-width: 768px) {
    .post-row {
      margin: 0 auto;
    }

    .image-col {
      margin-bottom: 0;
      margin-right: 16px;
    }
  }
</style>

<div class="filbert-flex-grid post-row">
  {#if post.getIn(['meta','imageNode'])}
    <div class="image-col">
      <a rel=prefetch href="/public/{post.get('canonical')}">
        <Image
            node={post.getIn(['meta','imageNode'])}
            hideBorder
            hideCaption
            postListOverride
        />
      </a>
    </div>
  {/if}
  <div class="details-col">
    <a rel=prefetch class="filbert-link-alt heading-link" href="/public/{post.get('canonical')}">
      {post.get('title')}
    </a>
    {#if post.get('abstract')}
      <div class="post-abstract-row">
        <a rel=prefetch class="filbert-link-alt abstract-link" href="/public/{post.get('canonical')}">
          {post.get('abstract')}
        </a>
      </div>
    {/if}
    <div class="post-meta-row">
      <div class="post-action-container">
        <PostAvatar post={post} postIsPrivate={postIsPrivate} />
      </div>
      {#if post.get('canEdit')}
        <div class="post-action-container">
          <a rel=prefetch class="filbert-nav-button post-action-link" href={nextUrl}>
            manage
          </a>
        </div>
      {/if}
      {#if !postIsPrivate && post.get('canEdit')}
        <div class="post-action-container" style="--padding-left: 0px;">
          <a rel=prefetch class="filbert-nav-button post-action-link" href={`/edit/${post.get('id')}`}>
            edit
          </a>
        </div>
      {/if}
      <div class="post-action-container">
        <AuthorExpand username={post.get('username')} />
      </div>
    </div>
  </div>
</div>

// frontend/src/common/components/post-list-row.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import styled from 'styled-components';
import {
  backgroundColorSecondary,
  getVar,
  viewport7,
} from '../../variables.css';
import { createNextUrl } from '../dom';
import { AbstractLink, StyledHeadingA } from './layout-styled-components';
import PostAvatar from './post-avatar';
import Image from './image';
import { AuthorExpand, FlexGrid } from './shared-styled-components';
import {
  metaFontMixin,
  navButtonMixin,
} from './shared-styled-components-mixins';

const PostRow = styled(FlexGrid)`
  max-width: ${viewport7};
  padding: 16px 0;
  border-top: 1px solid ${getVar(backgroundColorSecondary)};
  align-items: center;
  &:last-of-type {
    margin-bottom: 42px;
  }
  @media (min-width: ${viewport7}) {
    margin: 0 auto;
  }
`;
const ImageCol = styled.div`
  padding: 0;
  flex: 1;
  margin-bottom: 16px;
  @media (min-width: ${viewport7}) {
    margin-bottom: 0;
    margin-right: 16px;
  }
`;
const DetailsCol = styled.div`
  padding: 0;
  flex: 4;
`;
const PostAbstractRow = styled.div`
  margin-top: 4px;
`;
const PostMetaRow = styled.div`
  display: flex;
  align-items: center;
  margin-top: 8px;
`;
const PostActionContainer = styled.div`
  position: relative;
  min-height: 18px;
  display: inline-block;
  padding-left: ${(p) => (p.noPadding ? '0' : '8px')};
  &:first-of-type {
    padding-left: 0;
  }
`;
const PostActionLink = styled(Link)`
  ${navButtonMixin};
  ${metaFontMixin};
  padding: 6px 8px;
`;
const PostImage = styled(Image)`
  margin: 0 auto;
  max-width: 300px;
  max-height: 300px;
  @media (min-width: ${viewport7}) {
    max-width: 150px;
    max-height: 150px;
  }
`;

export default React.memo(({ post, postIsPrivate }) => {
  return (
    <PostRow>
      {post.getIn(['meta', 'imageNode']) && (
        <ImageCol>
          <Link
            to={
              postIsPrivate
                ? `/edit/${post.get('id')}`
                : `/p/${post.get('canonical')}`
            }
          >
            <PostImage
              node={post.getIn(['meta', 'imageNode'])}
              hideBorder
              hideCaption
            />
          </Link>
        </ImageCol>
      )}
      <DetailsCol>
        <StyledHeadingA
          href={
            postIsPrivate
              ? `/edit/${post.get('id')}`
              : `/p/${post.get('canonical')}`
          }
        >
          {post.get('title')}
        </StyledHeadingA>
        <PostAbstractRow>
          <AbstractLink
            href={
              postIsPrivate
                ? `/edit/${post.get('id')}`
                : `/p/${post.get('canonical')}`
            }
          >
            {post.get('abstract')}
          </AbstractLink>
        </PostAbstractRow>
        <PostMetaRow>
          <PostActionContainer>
            <PostAvatar post={post} postIsPrivate={postIsPrivate} />
          </PostActionContainer>
          {post.get('canEdit') && (
            <PostActionContainer>
              <PostActionLink to={createNextUrl(`/manage/${post.get('id')}`)}>
                manage
              </PostActionLink>
            </PostActionContainer>
          )}
          {!postIsPrivate && post.get('canEdit') && (
            <PostActionContainer noPadding>
              <PostActionLink to={`/edit/${post.get('id')}`}>
                edit
              </PostActionLink>
            </PostActionContainer>
          )}
          <PostActionContainer>
            <AuthorExpand to={`/public?username=${post.get('username')}`}>
              {post.get('username')}
            </AuthorExpand>
          </PostActionContainer>
        </PostMetaRow>
      </DetailsCol>
    </PostRow>
  );
});
