// sapper/src/form-components/Toggle.svelte
<script>
  export let value;
  export let onUpdate;
  export let label;
  export let disabled;

  let isFocused;
</script>

<style>
  .wrapper {
    display: flex;
    align-items: center;
    margin-bottom: 8px;
  }
  .toggle-wrapper {
    display: flex;
    flex-shrink: 0;
    align-items: center;
    position: relative;
    background-color: transparent;
    transition: background-color 0.125s ease-out;
    padding-left: 1px;
    padding-right: 1px;
    margin-left: 8px;
    border-radius: 32px;
    border: 1px solid var(--background-color-secondary);
    width: 64px;
    height: 34px;
  }
  .toggle-wrapper:hover {
    cursor: pointer;
  }
  .toggle-focused {
    outline: var(--filbert-outline);
  }
  .toggle-value {
    background-color: var(--accent-color-primary);
  }
  .toggle-disabled {
    background-color: var(--background-color-secondary);
  }
  .toggle-disabled:hover {
    cursor: not-allowed;
  }
  .knob {
    position: absolute;
    left: 34px;
    transition: left 0.125s ease-out;
    background-color: var(--filbert-abramovTextWhite);
    box-shadow: var(--filbert-box-shadow);
    border-radius: 50%;
    height: 32px;
    width: 32px;
  }
  .knob-no-value {
    left: 1px;
  }
  label {
    flex-grow: 2;
  }
  input {
    position: absolute;
    height: 0;
    width: 0;
    opacity: 0;
  }
</style>

<div class="wrapper">
  {#if label}
    <label>{label}</label>
  {:else}
    <slot />
  {/if}
  <div
    class="toggle-wrapper"
    class:toggle-value="{value}"
    class:toggle-disabled="{disabled}"
    class:toggle-focused="{isFocused}"
    on:click="{() => !disabled && onUpdate()}"
  >
    <div class="knob" class:knob-no-value="{!value}"></div>
    <input
      type="checkbox"
      bind:checked="{value}"
      {disabled}
      on:focus="{() => (isFocused = true)}"
      on:blur="{() => (isFocused = false)}"
      on:change="{onUpdate}"
    />
  </div>
</div>

// frontend/src/common/components/toggle.jsx
import React, { useState } from 'react';
import styled, { css } from 'styled-components';
import {
  abramovTextWhite,
  accentColorPrimary,
  backgroundColorSecondary,
  boxShadow,
  getVar,
  outline,
} from '../../variables.css';
import { ease } from '../css';

const Wrapper = styled.div`
  display: flex;
  align-items: center;
  margin-bottom: 8px;
`;
const ToggleWrapper = styled.div`
  display: flex;
  flex-shrink: 0;
  align-items: center;
  position: relative;
  outline: ${(p) => p.isFocused && getVar(outline)};
  background-color: ${(p) =>
    p.value ? getVar(accentColorPrimary) : 'transparent'};
  ${ease('background-color')};
  padding-left: 1px;
  padding-right: 1px;
  margin-left: 8px;
  border-radius: 32px;
  border: 1px solid ${getVar(backgroundColorSecondary)};
  width: 64px;
  height: 34px;
  &:hover {
    cursor: ${(p) => (p.disabled ? 'not-allowed' : 'pointer')};
  }
  ${(p) =>
    p.disabled &&
    css`
      background-color: ${getVar(backgroundColorSecondary)};
    `}
`;
const Knob = styled.div`
  position: absolute;
  left: 34px;
  ${ease('left')};
  background-color: ${abramovTextWhite};
  box-shadow: ${getVar(boxShadow)};
  border-radius: 50%;
  height: 32px;
  width: 32px;
  ${(p) =>
    !p.value &&
    css`
      left: 1px;
    `}
`;
const Label = styled.label`
  flex-grow: 2;
`;
const HiddenCheckbox = styled.input`
  position: absolute;
  height: 0;
  width: 0;
  opacity: 0;
`;

export default React.memo(({ value, onUpdate, label, children, disabled }) => {
  const [isFocused, setIsFocused] = useState(false);

  return (
    <Wrapper>
      {children || <Label>{label}</Label>}
      <ToggleWrapper
        value={value}
        disabled={disabled}
        onClick={() => !disabled && onUpdate()}
        isFocused={isFocused}
      >
        <Knob value={value} />
        <HiddenCheckbox
          key={`checkbox${value}`}
          type="checkbox"
          checked={!!value}
          disabled={disabled}
          onFocus={() => setIsFocused(true)}
          onBlur={() => setIsFocused(false)}
          onChange={onUpdate}
        />
      </ToggleWrapper>
    </Wrapper>
  );
});
