// frontend/src/pages/private.jsx
import { fromJS, List } from 'immutable';
import React from 'react';
import { FlexGrid } from '../common/components/shared-styled-components';

import { apiGet } from '../common/fetch';
import { formatPostDate } from '../common/utils';

import Header from './header';
import Footer from './footer';
import {
  Article,
  StyledHeadingA,
} from '../common/components/layout-styled-components';
import {
  BaseRow,
  ColFilter,
  Filter,
  FilterInput,
  FilterWithInput,
  StyledH2,
  StyledH3,
} from '../common/components/list-all-styled-components';

import PostListRow from '../common/components/post-list-row';

export default class PrivatePosts extends React.Component {
  containsInputRef = React.createRef();

  constructor(props) {
    super(props);

    this.state = {
      drafts: List(),
      oldestFilterIsSelected: false,
      containsFilterIsSelected: false,
      contains: '',
      randomFilterIsSelected: false,
      loading: false,
    };
  }

  async componentDidMount() {
    this.syncQueryParamsAndLoadDrafts();
  }

  async componentDidUpdate() {
    const queryParams = new URLSearchParams(window.location.search);
    if (queryParams.toString() !== this.prevQueryParams.toString()) {
      this.syncQueryParamsAndLoadDrafts();
    }
  }

  syncQueryParamsAndLoadDrafts = async () => {
    const queryParams = new URLSearchParams(window.location.search);
    this.prevQueryParams = queryParams;
    this.setState(
      {
        oldestFilterIsSelected: queryParams.has('oldest'),
        containsFilterIsSelected: queryParams.has('contains'),
        contains: queryParams.get('contains') || '',
        randomFilterIsSelected: queryParams.has('random'),
      },
      this.loadDrafts
    );
  };

  loadDrafts = async () => {
    const {
      state: {
        loading,
        contains,
        randomFilterIsSelected: random,
        oldestFilterIsSelected: oldest,
      },
    } = this;
    if (loading) {
      return;
    }
    await new Promise((resolve) => this.setState({ loading: true }, resolve));
    const queryParams = new URLSearchParams(window.location.search);
    queryParams.delete('contains');
    queryParams.delete('random');
    queryParams.delete('oldest');
    if (contains) {
      queryParams.set('contains', contains);
    }
    if (random) {
      queryParams.set('random', '');
    }
    if (oldest) {
      queryParams.set('oldest', '');
    }
    const queryString =
      queryParams.toString().length > 0 ? `?${queryParams.toString()}` : '';
    // update the URL in history for the user to retain
    window.history.pushState(
      {},
      document.title,
      `${window.location.pathname}${queryString}`
    );
    const { error, data: drafts } = await apiGet(`/draft${queryString}`);
    if (!error) {
      const postsFormatted = fromJS(
        drafts.map((draft) => ({
          ...draft,
          updated: formatPostDate(draft.updated),
        }))
      );
      this.setState({ drafts: postsFormatted });
    }
    this.setState({ loading: false });
  };

  loadDraftsDebounce = async () => {
    if (this.containsTimeout) {
      clearTimeout(this.containsTimeout);
    }
    this.containsTimeout = setTimeout(this.loadDrafts, 750);
  };

  toggleOldestFilter = () => {
    const {
      state: { oldestFilterIsSelected, loading },
    } = this;
    if (loading) {
      return;
    }
    this.setState(
      { oldestFilterIsSelected: !oldestFilterIsSelected },
      this.loadDrafts
    );
  };

  toggleRandomFilter = () => {
    const {
      state: { randomFilterIsSelected, loading },
    } = this;
    if (loading) {
      return;
    }
    this.setState(
      { randomFilterIsSelected: !randomFilterIsSelected },
      this.loadDrafts
    );
  };

  toggleContainsFilter = () => {
    const {
      state: { containsFilterIsSelected, loading },
    } = this;
    if (loading) {
      return;
    }
    this.setState(
      {
        containsFilterIsSelected: !containsFilterIsSelected,
        contains: '',
      },
      () => {
        if (!containsFilterIsSelected) {
          this.containsInputRef.current.focus();
        } else {
          this.loadDrafts();
        }
      }
    );
  };

  updateContains = (event) => {
    const {
      target: { value },
    } = event;
    const {
      state: { contains, loading },
    } = this;
    if (loading) {
      return;
    }
    this.setState({ contains: value }, () => {
      if (value === contains || value.length < 3) {
        return;
      }
      this.loadDraftsDebounce();
    });
  };

  render() {
    const {
      state: {
        loading,
        drafts,
        oldestFilterIsSelected,
        containsFilterIsSelected,
        contains,
        randomFilterIsSelected,
      },
      props: { session, setSession },
    } = this;

    return (
      <>
        <Header session={session} setSession={setSession} />
        <Article>
          <>
            <BaseRow>
              <StyledH2>My Private Work</StyledH2>
              <StyledH3>
                These pieces have{' '}
                <span role="img" aria-label="lock">
                  🔒
                </span>{' '}
                NOT been published{' '}
                <span role="img" aria-label="lock">
                  🔑
                </span>{' '}
                and are only viewable{' '}
                <span role="img" aria-label="eyeballs">
                  👀
                </span>{' '}
                by you while logged into{' '}
                <span role="img" aria-label="hand writing with a pen">
                  ✍️
                </span>{' '}
                filbert
              </StyledH3>
            </BaseRow>
            <BaseRow loading={loading ? 1 : undefined}>
              <StyledH3>Filter by:</StyledH3>
              <FlexGrid>
                <ColFilter>
                  <Filter
                    isOpen={!oldestFilterIsSelected}
                    onClick={this.toggleOldestFilter}
                  >
                    newest ⇩
                  </Filter>
                  <Filter
                    isOpen={oldestFilterIsSelected}
                    onClick={this.toggleOldestFilter}
                  >
                    oldest ⇧
                  </Filter>
                  <Filter
                    isOpen={randomFilterIsSelected}
                    onClick={this.toggleRandomFilter}
                  >
                    random ?
                  </Filter>
                </ColFilter>
                <ColFilter>
                  <FilterWithInput
                    isOpen={containsFilterIsSelected}
                    onClick={this.toggleContainsFilter}
                  >
                    contains:
                  </FilterWithInput>
                  <FilterInput
                    ref={this.containsInputRef}
                    shouldHide={!containsFilterIsSelected}
                    name="post-text"
                    type="text"
                    value={contains}
                    onChange={this.updateContains}
                    autoComplete="off"
                  />
                </ColFilter>
              </FlexGrid>
            </BaseRow>
            {drafts.size === 0 && (
              <BaseRow>
                <StyledHeadingA href="/edit/new">
                  <span role="img" aria-label="magnifying glass">
                    🔍
                  </span>{' '}
                  Clear Filters or Click Here or the &quot;new&quot; menu button
                  above to start a new Private piece
                </StyledHeadingA>
              </BaseRow>
            )}
            {drafts.map((draft) => (
              <PostListRow key={draft.get('id')} post={draft} />
            ))}
          </>
        </Article>
        <Footer />
      </>
    );
  }
}

// web/src/routes/private/index.svelte
<script context="module">
  import { loadPosts } from '../../common/post-list-helpers';

  let oldestFilterIsSelected;
  let randomFilterIsSelected;
  let containsFilterIsSelected;
  let contains = '';

  export async function preload({ query = {} }, session) {
    const posts = await loadPosts(
      '/draft',
      new URLSearchParams(query),
      this.fetch
    );

    return {
      posts,
      oldestFilterIsSelected: query.oldest !== undefined,
      randomFilterIsSelected: false,
      containsFilterIsSelected: !!query.contains,
      contains: query.contains || '',
    };
  }
</script>

<script>
  export let posts;
  export let oldestFilterIsSelected;
  export let randomFilterIsSelected;
  export let containsFilterIsSelected;
  export let contains = '';

  import { pushHistory } from '../../common/post-list-helpers';

  import H2 from '../../document-components/H2.svelte';
  import H1 from '../../document-components/H1.svelte';
  import H3 from '../../document-components/H3.svelte';
  import PostListRow from '../../list-components/PostListRow.svelte';

  let responsePromise = Promise.resolve(posts);
  let totalPosts = posts.length;

  $: {
    responsePromise.then((p) => {
      totalPosts = p.length;
    });
  }

  function toggleOldestFilter() {
    oldestFilterIsSelected = !oldestFilterIsSelected;
    const updatedUrlSearchParams = pushHistory(
      'oldest',
      oldestFilterIsSelected
    );
    responsePromise = loadPosts(updatedUrlSearchParams);
  }
  function toggleRandomFilter() {
    /*TODO*/
  }
  let containsInputDomNode;
  function toggleContainsFilter() {
    contains = '';
    const updatedUrlSearchParams = pushHistory('contains', contains);
    containsFilterIsSelected = !containsFilterIsSelected;
    if (containsFilterIsSelected) {
      containsInputDomNode.focus();
    } else {
      responsePromise = loadPosts(updatedUrlSearchParams);
    }
  }
  function updateContains(e) {
    contains = e.target.value;
    pushHistory('contains', contains);
    const updatedUrlSearchParams = pushHistory('contains', contains);
    responsePromise = loadPosts(updatedUrlSearchParams);
  }
</script>

<style>
  .base-row {
    max-width: var(--filbert-viewport7);
    padding: 16px 0;
    border-top: 1px solid var(--background-color-secondary);
    word-wrap: break-word;
    word-break: break-word;
  }
  .base-row:first-of-type {
    border: none;
    padding-top: 0;
  }
  .base-row:last-of-type {
    margin-bottom: 42px;
  }
  .col-filter {
    display: flex;
    padding-bottom: 16px;
    white-space: nowrap;
  }
  .col-filter:last-of-type {
    padding-bottom: 0;
  }
  button {
    display: inline-block;
    padding: 9px;
    margin-left: 8px;
  }
  button:first-of-type {
    margin-left: 0;
  }
  input {
    flex: 1;
    height: 38px;
    margin-right: 8px;
    transition: opacity 0.2s;
    opacity: 1;
    /* outline: var(--filbert-outline); */
    border: 1px solid var(--filbert-lightBlue);
    border-left: none;
    border-radius: 0 26px 26px 0;
  }
  input.hide {
    opacity: 0;
  }
  .with-input {
    flex-grow: 0;
    border: 1px solid transparent;
    border-right: none;
    margin-right: 0;
  }
  .with-input.open {
    border: 1px solid var(--accent-color-primary);
    border-right: none;
    margin-right: 0;
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
  }

  @media (min-width: 768px) {
    .base-row {
      margin: 0 auto;
    }
  }
  @media (min-width: 992px) {
    .col-filter:last-of-type {
      padding-bottom: 16px;
    }
  }
</style>

<svelte:head>
  <title>filbert | private work</title>
</svelte:head>

<div class="base-row">
  <H1>My Private Work ({totalPosts})</H1>
  <H3 fontWeightNormal>
    These pieces have{' '}
    <span role="img" aria-label="lock">🔒</span>
    {' '} NOT been published{' '}
    <span role="img" aria-label="lock">🔑</span>
    {' '} and are only viewable{' '}
    <span role="img" aria-label="eyeballs">👀</span>
    {' '} by you while logged into{' '}
    <span role="img" aria-label="hand writing with a pen">✍️</span>
    {' '} filbert
  </H3>
</div>
<div class="base-row">
  <H2>Filter by:</H2>
  <div class="filbert-flex-grid">
    <div class="filbert-col col-filter">
      <button
        class="filbert-nav-button"
        class:open="{!oldestFilterIsSelected}"
        on:click="{toggleOldestFilter}"
      >
        newest ⇩
      </button>
      <button
        class="filbert-nav-button"
        class:open="{oldestFilterIsSelected}"
        on:click="{toggleOldestFilter}"
      >
        oldest ⇧
      </button>
      <button
        class="filbert-nav-button"
        class:open="{randomFilterIsSelected}"
        on:click="{toggleRandomFilter}"
      >
        random ?
      </button>
    </div>
    <div class="filbert-col col-filter">
      <button
        class="filbert-nav-button with-input"
        class:open="{containsFilterIsSelected}"
        on:click="{toggleContainsFilter}"
      >
        contains
      </button>
      <input
        class:hide="{!containsFilterIsSelected}"
        on:input="{updateContains}"
        bind:this="{containsInputDomNode}"
        value="{contains}"
        name="contains"
        type="text"
      />
    </div>
  </div>
</div>
{#await responsePromise}
  <p class="filbert-section">...public</p>
{:then posts}
  {#if posts && !posts.length}
    <div class="base-row">
      <h3 class="filbert-section heading-link">
        <span role="img" aria-label="crying face">😢</span>
        {' '} Nada. 没有. Rien. ничего. Nothing. ナッシング...
      </h3>
    </div>
  {/if}
  {#each posts as post}
    <PostListRow {post} />
  {/each}
{:catch error}
  <p style="color: red">{error.message}</p>
{/await}
