// sapper/src/routes/public/index.svelte
<script context="module">
  import { fromJS } from 'immutable';

  import { API_URL } from '../../common/constants';
  import { formatPostDate } from '../../common/utils';
  import { getApiClientInstance } from '../../common/api-client';
  import { loading } from '../../stores';

  let apiClient;

  let oldestFilterIsSelected;
  let randomFilterIsSelected;
  let usernameFilterIsSelected;
  let username = '';

  function pushHistory(param, value) {
    const urlSearchParams = new URLSearchParams(window.location.search);
    if (value) {
      urlSearchParams.set(param, value === true ? '' : value)
    } else {
      urlSearchParams.delete(param);
    }
    const updatedQueryString =
        urlSearchParams.toString().length > 0 ? `?${urlSearchParams.toString()}` : '';
    // update the URL in history for the user to retain
    window.history.pushState(
        {},
        document.title,
        `${window.location.pathname}${updatedQueryString}`
    );
    return urlSearchParams;
  }

  function loadPosts(urlSearchParams) {
    loading.set(true);
    const params = urlSearchParams.toString();
    const queryString =
        params.length > 0 ? `?${params}` : '';
    return apiClient.get(`${API_URL}/post${queryString}`)
        .then(({error, data: postsData}) => {
          return {
            posts: postsData.map((post) => fromJS({
              ...post,
              published: formatPostDate(post.published),
              updated: formatPostDate(post.updated),
            }))
          }
        })
        .finally(() => loading.set(false))
  }

  export function preload(page, session, preloading) {
    const { path, params, query = {} } = page;
    apiClient = getApiClientInstance(this.fetch);

    const responsePromise = loadPosts(new URLSearchParams(query))

    return {
      responsePromise,
      oldestFilterIsSelected: query.oldest !== undefined,
      randomFilterIsSelected: false,
      usernameFilterIsSelected: query.username,
      username: query.username || '',
    };
  }
</script>

<script>
  export let responsePromise;
  export let oldestFilterIsSelected;
  export let randomFilterIsSelected;
  export let usernameFilterIsSelected;
  export let username = '';

  import H2 from '../../document-components/H2.svelte';
  import H1 from '../../document-components/H1.svelte';
  import H3 from '../../document-components/H3.svelte';
  import PostListRow from '../../post-components/PostListRow.svelte';

  function toggleOldestFilter() {
    oldestFilterIsSelected = !oldestFilterIsSelected;
    const updatedUrlSearchParams = pushHistory('oldest', oldestFilterIsSelected);
    responsePromise = loadPosts(updatedUrlSearchParams);
  }
  function toggleRandomFilter() {/*TODO*/}
  let usernameInputDomNode;
  function toggleUsernameFilter() {
    username = '';
    const updatedUrlSearchParams = pushHistory('username', username);
    usernameFilterIsSelected = !usernameFilterIsSelected;
    if (usernameFilterIsSelected) {
      usernameInputDomNode.focus();
    } else {
      responsePromise = loadPosts(updatedUrlSearchParams);
    }
  }
  function updateUsername(e) {
    username = e.target.value;
    pushHistory('username', username);
    const updatedUrlSearchParams = pushHistory('username', username);
    responsePromise = loadPosts(updatedUrlSearchParams);
  }
</script>

<style>
  .base-row {
    max-width: var(--filbert-viewport7);
    padding: 16px 0;
    border-top: 1px solid var(--background-color-secondary);
    word-wrap: break-word;
    word-break: break-word;
  }
  .base-row:first-of-type {
     border: none;
     padding-top: 0;
   }
  .base-row:last-of-type {
     margin-bottom: 42px;
   }
  .col-filter {
    display: flex;
    padding-bottom: 16px;
    white-space: nowrap;
  }
  .col-filter:last-of-type {
     padding-bottom: 0;
   }
  button {
    display: inline-block;
    padding: 9px;
    margin-left: 8px;
  }
  button:first-of-type {
     margin-left: 0;
  }
  input {
    flex: 1;
    height: 38px;
    margin-right: 8px;
    transition: opacity 0.2s;
    opacity: 1;
    /* outline: var(--filbert-outline); */
    border: 1px solid var(--filbert-lightBlue);
    border-left: none;
    border-radius: 0 26px 26px 0;
  }
  input.hide {
    opacity: 0;
  }
  .with-input {
    flex-grow: 0;
    border: 1px solid transparent;
    border-right: none;
    margin-right: 0;
  }
  .with-input.open {
    border: 1px solid var(--accent-color-primary);
    border-right: none;
    margin-right: 0;
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
  }

  @media (min-width: 768px) {
    .base-row {
      margin: 0 auto;
    }
  }
  @media (min-width: 992px) {
    .col-filter:last-of-type {
      padding-bottom: 16px;
    }
  }
</style>

<div class="base-row">
  <H1>Public Articles</H1>
  <H3 fontWeightNormal>
    These pieces have been published{' '}
    <span role="img" aria-label="stack of books">
                      📚
                    </span>{' '}
    and are viewable by everyone on the World Wide Web{' '}
    <span role="img" aria-label="globe">
                      🌍
                    </span>
  </H3>
</div>
<div class="base-row">
  <H2>Filter by:</H2>
  <div class="filbert-flex-grid">
    <div class="filbert-col col-filter">
      <button class="filbert-nav-button" class:open={!oldestFilterIsSelected} on:click={toggleOldestFilter}>
        newest ⇩
      </button>
      <button class="filbert-nav-button" class:open={oldestFilterIsSelected} on:click={toggleOldestFilter}>
        oldest ⇧
      </button>
      <button class="filbert-nav-button" class:open={randomFilterIsSelected} on:click={toggleRandomFilter}>
        random ?
      </button>
    </div>
    <div class="filbert-col col-filter">
      <button class="filbert-nav-button with-input" class:open={usernameFilterIsSelected} on:click={toggleUsernameFilter}>username @</button>
      <input
          class:hide={!usernameFilterIsSelected}
          on:input={updateUsername}
          bind:this={usernameInputDomNode}
          value={username}
          name="username"
          type="text"
          autoComplete="off"
          minlength="5"
          maxlength="42"
      />
    </div>
  </div>
</div>
{#await responsePromise}
  <p>...public</p>
{:then {posts}}
  {#if posts && !posts.length}
    <div class="base-row">
      <h3 class="filbert-section heading-link">
        <span role="img" aria-label="crying face">
                      😢
                    </span>{' '}
        Nada. 没有. Rien. ничего. Nothing. ナッシング...
      </h3>
    </div>
  {/if}
  {#each posts as post}
    <PostListRow {post} />
  {/each}
{:catch error}
  <p style="color: red">{error.message}</p>
{/await}

// frontend/src/pages/public.jsx
import { fromJS, List } from 'immutable';
import React from 'react';
import styled from 'styled-components';
import {
  Article,
  NavSpan
} from '../common/components/layout-styled-components';
import {
  AuthorExpand,
  PostAbstractRow,
  PostAction,
  PostActionA,
  PostMetaContentFirst,
  PostMetaRow,
  PostRow,
  StyledA,
  StyledH2,
  StyledH3,
  StyledHeadingA
} from '../common/components/list-all-styled-components';
import { Input } from '../common/components/shared-styled-components';
import { lightBlue } from '../common/css';

import { apiDelete, apiGet } from '../common/fetch';
import { confirmPromise, formatPostDate } from '../common/utils';
import Footer from './footer';

import Header from './header';

const FilterContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-around;
`;
const Filter = styled(NavSpan)`
  padding: 9px;
  margin: 8px;
`;
const UsernameFilter = styled(Filter)`
  border: 1px solid transparent;
  border-right: none;
  margin-right: 0;
  ${p =>
    p.isOpen &&
    `
    border: 1px solid ${lightBlue};
    border-right: none;
    margin-right: 0;
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
  `}
`;
const InputStyled = styled(Input)`
  height: 36px;
  margin-right: 8px;
  transition: opacity 0.2s;
  opacity: 1;
  //outline: 0; // outline is ugly but, a11y
  border: 1px solid ${lightBlue};
  border-left: none;
  border-radius: 0 26px 26px 0;
  ${p =>
    p.shouldHide &&
    `
    opacity: 0;
  `}
`;

export default class Public extends React.Component {
  usernameInputRef = React.createRef();

  constructor(props) {
    super(props);

    const queryParams = new URLSearchParams(window.location.search);
    this.state = {
      posts: List(),
      oldestFilterIsSelected: queryParams.has('oldest'),
      usernameFilterIsSelected: queryParams.has('username'),
      username: queryParams.get('username') || '',
      randomFilterIsSelected: queryParams.has('random')
    };
  }

  async componentDidMount() {
    this.loadPosts();
  }

  deletePost = async post => {
    try {
      await confirmPromise(`Delete post ${post.get('title')}?`);
      await apiDelete(`/post/${post.get('id')}`);
      this.loadPosts();
    } catch (err) {
      console.error('Delete post error:', err);
    }
  };

  loadPosts = async () => {
    const {
      state: {
        username,
        randomFilterIsSelected: random,
        oldestFilterIsSelected: oldest
      }
    } = this;
    const queryParams = new URLSearchParams(window.location.search);
    queryParams.delete('username');
    queryParams.delete('random');
    queryParams.delete('oldest');
    if (username) {
      queryParams.set('username', username);
    }
    if (random) {
      queryParams.set('random', '');
    }
    if (oldest) {
      queryParams.set('oldest', '');
    }
    const queryString =
      queryParams.toString().length > 0 ? `?${queryParams.toString()}` : '';
    // update the URL in history for the user to retain
    window.history.pushState(
      {},
      document.title,
      `${window.location.pathname}${queryString}`
    );
    const posts = await apiGet(`/post${queryString}`);
    const postsFormatted = fromJS(
      posts.map(post => ({
        ...post,
        published: formatPostDate(post.published),
        updated: formatPostDate(post.updated)
      }))
    );
    this.setState({ posts: postsFormatted });
  };

  loadPostsDebounce = async () => {
    if (this.checkUsernameTimeout) {
      clearTimeout(this.checkUsernameTimeout);
    }
    this.checkUsernameTimeout = setTimeout(this.loadPosts, 750);
  };

  toggleOldestFilter = () => {
    const {
      state: { oldestFilterIsSelected }
    } = this;
    this.setState(
      { oldestFilterIsSelected: !oldestFilterIsSelected },
      this.loadPosts
    );
  };

  toggleRandomFilter = () => {
    const {
      state: { randomFilterIsSelected }
    } = this;
    this.setState(
      { randomFilterIsSelected: !randomFilterIsSelected },
      this.loadPosts
    );
  };

  toggleUsernameFilter = () => {
    const {
      state: { usernameFilterIsSelected }
    } = this;
    this.setState(
      {
        usernameFilterIsSelected: !usernameFilterIsSelected,
        username: ''
      },
      () => {
        if (!usernameFilterIsSelected) {
          this.usernameInputRef.current.focus();
        } else {
          this.loadPosts();
        }
      }
    );
  };

  updateUsername = event => {
    const {
      target: { value }
    } = event;
    const {
      state: { username }
    } = this;
    const newUsername = value.replace(/[^0-9a-z]/g, '');
    this.setState({ username: newUsername }, () => {
      if (
        newUsername === username ||
        newUsername.length < 5 ||
        newUsername.length > 42
      ) {
        return;
      }
      this.loadPostsDebounce();
    });
  };

  render() {
    const {
      state: {
        posts,
        oldestFilterIsSelected,
        usernameFilterIsSelected,
        username,
        randomFilterIsSelected
      },
      props: { session, setSession }
    } = this;

    return (
      <>
        <Header session={session} setSession={setSession} />
        <Article>
          <>
            <PostRow>
              <StyledH2>Public Articles</StyledH2>
              <StyledH3>
                These pieces have been published{' '}
                <span role="img" aria-label="stack of books">
                  📚
                </span>{' '}
                and are viewable by everyone on the World Wide Web{' '}
                <span role="img" aria-label="globe">
                  🌍
                </span>
              </StyledH3>
            </PostRow>
            <PostRow>
              <StyledH3>Filter by:</StyledH3>
              <FilterContainer>
                <Filter
                  isOpen={!oldestFilterIsSelected}
                  onClick={this.toggleOldestFilter}
                >
                  newest ⇩
                </Filter>
                <Filter
                  isOpen={oldestFilterIsSelected}
                  onClick={this.toggleOldestFilter}
                >
                  oldest ⇧
                </Filter>
                <Filter
                  isOpen={randomFilterIsSelected}
                  onClick={this.toggleRandomFilter}
                >
                  random ?
                </Filter>
                <div>
                  <UsernameFilter
                    isOpen={usernameFilterIsSelected}
                    onClick={this.toggleUsernameFilter}
                  >
                    username @
                  </UsernameFilter>
                  <InputStyled
                    ref={this.usernameInputRef}
                    shouldHide={!usernameFilterIsSelected}
                    name="username"
                    type="text"
                    value={username}
                    onChange={this.updateUsername}
                    autoComplete="off"
                    minLength="5"
                    maxLength="42"
                  />
                </div>
              </FilterContainer>
            </PostRow>
            {posts.size === 0 && (
              <PostRow>
                <StyledHeadingA>
                  <span role="img" aria-label="crying face">
                    😢
                  </span>{' '}
                  Nada. 没有. Rien. ничего. Nothing. ナッシング...
                </StyledHeadingA>
              </PostRow>
            )}
            {posts.map(post => (
              <PostRow key={`${post.get('id')}${post.get('canonical')}`}>
                <StyledHeadingA href={`/p/${post.get('canonical')}`}>
                  {post.get('title')}
                </StyledHeadingA>
                <PostAbstractRow>
                  <StyledA href={`/p/${post.get('canonical')}`}>
                    {post.get('abstract')}
                  </StyledA>
                </PostAbstractRow>
                <PostMetaRow>
                  <PostMetaContentFirst>
                    {post.get('published')}
                  </PostMetaContentFirst>
                  {post.get('canEdit') && (
                    <>
                      <PostActionA href={`/edit/${post.get('id')}`}>
                        edit
                      </PostActionA>
                    </>
                  )}
                  {post.get('canDelete') && (
                    <>
                      <PostAction onClick={() => this.deletePost(post)}>
                        delete
                      </PostAction>
                    </>
                  )}
                  <AuthorExpand>{post.get('username')}</AuthorExpand>
                </PostMetaRow>
              </PostRow>
            ))}
          </>
        </Article>
        <Footer />
      </>
    );
  }
}
