// sapper/src/routes/signout.svelte
<script context="module">
  export async function preload(page, session) {
    // TODO: call API /signout
  }
</script>

<script>
  import H1 from '../document-components/H1.svelte';
</script>

<style>
  div {
    margin-top: 20vh;
    text-align: center;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .bigger {
    font-size: 72px;
  }
</style>

<div class="test">
  <H1>
    <span class="bigger">
      You're logged out
      <span role="img" aria-label="hand waving bye">👋</span>
    </span>
  </H1>
</div>

// frontend/src/pages/signout.jsx
import * as React from 'react';
import {
  H1Center,
  StaticFooter,
} from '../common/components/layout-styled-components';
import { signout } from '../common/session';
import Header from './header';
import Footer from './footer';

export default ({
  session,
  setSession,
  font,
  toggleFont,
  theme,
  toggleTheme,
}) => {
  if (session.get('userId')) {
    signout();
    setSession({});
  }

  return (
    <>
      <Header
        font={font}
        toggleFont={toggleFont}
        theme={theme}
        toggleTheme={toggleTheme}
      />
      <H1Center>
        {"You're logged out "}
        <span role="img" aria-label="hand waving bye">
          👋
        </span>
      </H1Center>
      <StaticFooter>
        <Footer />
      </StaticFooter>
    </>
  );
};
