// frontend/src/pages/signin.jsx
import * as React from 'react';
import { Link, Redirect } from 'react-router-dom';
import styled from 'styled-components';
import GoogleIconSvg from '../../assets/icons/google-logo.svg';
import { LogoLinkStyled } from '../common/components/layout-styled-components';

import {
  ButtonSpan,
  CancelButton,
  ErrorMessage,
  H1Styled,
  H3Styled,
  Input,
  InputContainer,
  Label,
  MessageContainer,
  ProfileImg,
  SuccessMessage
} from '../common/components/shared-styled-components';
import { darkGrey } from '../common/css';
import { loadScript } from '../common/dom';
import { apiGet } from '../common/fetch';
import ButtonSpinner from '../common/components/button-spinner';
import { sansSerif } from '../common/fonts.css';

import { signinGoogle, signout } from '../common/session';

const Container = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
`;
const SignInForm = styled.form`
  width: 40vw;
  max-width: 450px;
  min-width: 320px;
  padding: 40px;
  overflow: hidden;
  background-color: white;
  border-radius: 2px;
`;
const StyledLinkStyled = styled(LogoLinkStyled)`
  display: block;
  position: static;
  padding-bottom: 24px;
`;
const H1StyledStyled = styled(H1Styled)`
  margin-bottom: 8px;
`;
const H3StyledStyled = styled(H3Styled)`
  margin-bottom: 24px;
`;
const LinkStyled2 = styled(Link)`
  text-decoration: none;
`;
const Smaller = styled.span`
  display: block;
  font-family: inherit;
  font-size: smaller;
`;
const Smaller2 = styled(Smaller)`
  font-weight: 400;
  margin-top: 16px;
`;
const GoogleSigninButton = styled(ButtonSpinner)``;
const GoogleInfo = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  background: white;
  margin-bottom: 16px;
  font-size: 18px;
  &:hover {
    background: white;
  }
`;
const GoogleIcon = styled(GoogleIconSvg)`
  position: absolute;
  left: 16px;
  flex-shrink: 0;
  height: 24px;
  width: 24px;
`;
const GoogleInfoSpan = styled.span`
  font-family: ${sansSerif};
  display: block;
  color: ${darkGrey};
  overflow: hidden;
  white-space: pre-wrap;
  text-overflow: ellipsis;
  padding: 4px;
`;

const usernameRef = React.createRef();

export default class SignIn extends React.Component {
  GoogleAuth;

  constructor(props) {
    super(props);
    this.state = {
      loading: true,
      error: null,
      success: null,
      shouldRedirect: false,
      username: '',
      googleUser: {},
      shouldShowUsernameInput: false
    };
  }

  async componentDidMount() {
    if (usernameRef && usernameRef.current) {
      usernameRef.current.focus();
    }
    window.initThaGoog = async () => {
      this.setState({ loading: true });
      await new Promise(resolve => gapi.load('auth2', resolve));
      await gapi.auth2.init({
        client_id: process.env.GOOGLE_API_FILBERT_CLIENT_ID
      });
      this.GoogleAuth = gapi.auth2.getAuthInstance();
      if (this.GoogleAuth.isSignedIn.get()) {
        const user = this.GoogleAuth.currentUser.get();
        await this.setGoogleUser(user);
      }
      this.setState({ loading: false });
    };
    if (!this.GoogleAuth) {
      await loadScript(
        'https://apis.google.com/js/platform.js?onload=initThaGoog'
      );
    } else if (this.GoogleAuth.isSignedIn.get()) {
      const user = this.GoogleAuth.currentUser.get();
      this.setGoogleUser(user);
    }
    this.setState({ loading: false });
  }

  componentWillUnmount() {
    delete window.initThaGoog;
  }

  setGoogleUser = async user => {
    if (!user.getBasicProfile) {
      return Promise.resolve();
    }
    const profile = user.getBasicProfile();
    const googleUser = {
      name: profile.getName(),
      givenName: profile.getGivenName(),
      imageUrl: profile.getImageUrl(),
      email: profile.getEmail(),
      idToken: user.getAuthResponse().id_token
    };
    return new Promise(resolve =>
      this.setState({ googleUser }, () => resolve(googleUser))
    );
  };

  doLoginGoogle = async evt => {
    try {
      const {
        state: { googleUser, username }
      } = this;
      let currentUser;
      // evt is a 'submit' event, we don't want the page to reload
      evt.stopPropagation();
      evt.preventDefault();

      this.setState({ success: null, error: null, loading: true });

      if (!googleUser?.idToken) {
        // open google window to let the user select a user to login as, or to grant access
        const user = await this.GoogleAuth.signIn();
        currentUser = await this.setGoogleUser(user);
      } else {
        // user was already logged in and set in this.state
        currentUser = googleUser;
      }
      const { signupIsIncomplete, session } = await signinGoogle(
        currentUser,
        username
      );
      if (signupIsIncomplete) {
        this.setState(
          {
            shouldShowUsernameInput: true,
            error: null,
            success: null,
            loading: false
          },
          () => {
            usernameRef.current.focus();
          }
        );
        return;
      }
      this.setState({ success: 'All set 👍', error: null });
      setTimeout(() => {
        this.setState({ shouldRedirect: true }, () => {
          // set session on App state on the way out...
          this.props?.setSession?.(session);
        });
      }, 500);
    } catch (error) {
      this.setState({
        success: null,
        error: error?.error || error?.message || 'Error',
        loading: false
      });
    }
  };

  doLogout = async () => {
    this.setState({ error: null, success: null, loading: true });
    await this.GoogleAuth.signOut();
    signout();
    this.setState({ googleUser: {}, loading: false });
  };

  updateUsername = event => {
    const {
      target: { value }
    } = event;
    const {
      state: { username }
    } = this;
    const newUsername = value.replace(/[^0-9a-z]/g, '');
    if (newUsername === username) {
      return;
    }
    this.setState({ username: newUsername, error: null, loading: true }, () => {
      if (this.checkUsernameTimeout) {
        clearTimeout(this.checkUsernameTimeout);
      }
      if (newUsername.length < 5) {
        this.setState({
          error: `${newUsername} is too short.  Pick a username between 5 and 42 characters.`,
          success: null,
          loading: false
        });
        return;
      }
      if (newUsername.length > 42) {
        this.setState({
          error: `${newUsername} is too long.  Pick a username between 5 and 42 characters.`,
          success: null,
          loading: false
        });
        return;
      }
      this.checkUsernameTimeout = setTimeout(async () => {
        try {
          await apiGet(`/user/${newUsername}`);
          this.setState({
            error: `${newUsername} is taken`,
            success: null,
            loading: false
          });
        } catch (err) {
          this.setState({
            success: `"${newUsername}" is available 👍`,
            error: null,
            loading: false
          });
        }
      }, 750);
    });
  };

  render() {
    const {
      state: {
        loading,
        error,
        success,
        shouldRedirect,
        shouldShowUsernameInput,
        username,
        googleUser: { name, givenName, imageUrl, email }
      }
    } = this;
    if (shouldRedirect) {
      const queryParams = new URLSearchParams(window.location.search);
      const nextUrl = queryParams.get('next') || '/private'; // returns null if empty
      return <Redirect push to={nextUrl} />;
    }
    return (
      <Container>
        <SignInForm onSubmit={this.doLoginGoogle}>
          <StyledLinkStyled to="/">
            <span role="img" aria-label="hand writing with a pen">
              ✍️
            </span>{' '}
            filbert
          </StyledLinkStyled>
          <H1StyledStyled>Sign In</H1StyledStyled>
          {imageUrl && name && email && (
            <GoogleInfo>
              <ProfileImg src={imageUrl} />
              <GoogleInfoSpan>{name}</GoogleInfoSpan>
              <GoogleInfoSpan>
                <Smaller>{email}</Smaller>
              </GoogleInfoSpan>
            </GoogleInfo>
          )}
          {shouldShowUsernameInput && (
            <>
              <H3StyledStyled>
                Welcome!
                <Smaller2>
                  Just one more step before we continue - Choose a filbert
                  username.
                </Smaller2>
              </H3StyledStyled>
              <InputContainer>
                <Label htmlFor="username" error={error}>
                  filbert username (lowercase letters a-z and numbers 0-9 only,
                  length 5 to 42 characters)
                </Label>
                <Input
                  name="username"
                  type="text"
                  value={username}
                  onChange={this.updateUsername}
                  error={error}
                  ref={usernameRef}
                  autoComplete="off"
                  minLength="5"
                  maxLength="42"
                />
              </InputContainer>
            </>
          )}
          <MessageContainer>
            {error && (
              <ErrorMessage>
                Try again. {error}{' '}
                <span role="img" aria-label="male police officer">
                  👮
                </span>
              </ErrorMessage>
            )}
            {success && <SuccessMessage>{success}</SuccessMessage>}
          </MessageContainer>
          <GoogleSigninButton
            id="google-sign-in-button"
            type="submit"
            primary
            loading={loading}
            label={
              givenName || shouldShowUsernameInput
                ? `Continue as ${
                    shouldShowUsernameInput ? username : givenName
                  }`
                : 'Sign in to filbert with Google'
            }
          >
            <GoogleIcon />
          </GoogleSigninButton>
          {!shouldShowUsernameInput && givenName ? (
            <CancelButton type="button" onClick={this.doLogout}>
              <ButtonSpan>Logout</ButtonSpan>
            </CancelButton>
          ) : (
            <LinkStyled2 to="/">
              <CancelButton>
                <ButtonSpan>Cancel</ButtonSpan>
              </CancelButton>
            </LinkStyled2>
          )}
        </SignInForm>
      </Container>
    );
  }
}

// sapper/src/routes/signin.svelte
<script context="module">
  export function preload({query}) {
    return {isAdminLogin: query.admin !== undefined};
  }
</script>

<script>
  export let isAdminLogin;

  import { goto, stores } from '@sapper/app';
  import { onDestroy } from 'svelte';
  import { GoogleAuth } from '../stores';
  import { getGoogleUser } from '../common/google-auth';
  import { getApiClientInstance } from '../common/api-client';

  import ButtonSpinner from '../form-components/ButtonSpinner.svelte';

  import ProfileImg from '../user-components/ProfileImg.svelte';
  import H1 from '../document-components/H1.svelte';
  import H2 from '../document-components/H2.svelte';
  import H3 from '../document-components/H3.svelte';
  import GoogleLogoSvg from '../icons/google-logo.svelte';

  const { session } = stores();

  let usernameInputDomNode;
  let usernameAdminInputDomNode;
  let usernameValue = '';
  let username = '';
  let usernameIsInvalid = false;
  let shouldShowUsernameInput;
  let error;
  let success;
  let currentGoogleUser = {};
  let signinLoading = false;
  let signinButtonLabel;

  const googleAuthUnsubscribe = GoogleAuth.subscribe((auth) => {
    if (isAdminLogin) {
      return;
    }
    if (auth?.isSignedIn?.get?.()) {
      currentGoogleUser = getGoogleUser(auth?.currentUser?.get?.());
    } else {
      currentGoogleUser = {};
    }
  });

  onDestroy(googleAuthUnsubscribe)

  async function doLoginGoogle() {
    success = undefined;
    error = undefined;
    signinLoading = true;

    if (!currentGoogleUser.idToken) {
      // open google window to let the user select a user to login as, or to grant access
      try {
        const user = await $GoogleAuth.signIn();
        currentGoogleUser = getGoogleUser(user);
      } catch(err) {
        error = err;
        return;
      }
    }
    const {
      error: errorApi,
      signupIsIncomplete,
      ...filbertUser
    } = await getApiClientInstance(fetch).signinGoogle(currentGoogleUser, username);
    if (errorApi) {
      success = undefined;
      error = errorApi?.error || errorApi?.message || 'Error';
      signinLoading = false;
      return;
    }
    if (signupIsIncomplete) {
      shouldShowUsernameInput = true;
      error = undefined;
      success = undefined;
      signinLoading = false;
      usernameInputDomNode.focus();
      return;
    }
    session.set({ ...session, user: filbertUser });
    success = 'All set 👍';
    error = undefined;
    setTimeout(() => {
      // let some time pass to show the success message
      goto('/public/homepage');
    }, 400);
  }

  function doLogin() {
    alert("Admin")
  }

  function doLogout() {
    GoogleAuth.update(auth => auth.signOut());
  }

  $: {
    usernameValue = usernameValue.replace(/[^0-9a-z]/g, '').slice(0, 42);
    username = usernameValue;
    usernameIsInvalid = username.length < 5 || username.length > 42;
    error = undefined;
    success = undefined;
    if (isAdminLogin) {
      signinButtonLabel = 'Sign in to filbert';
    } else {
      signinButtonLabel = currentGoogleUser.givenName || shouldShowUsernameInput ? `Continue as ${shouldShowUsernameInput ? username : currentGoogleUser.givenName}` : 'Sign in to filbert with Google'
    }
  }
</script>

<style>
  section {
    display: flex;
    justify-content: center;
    align-items: center;
  }

  form {
    flex: 1;
    width: 40vw;
    max-width: 550px;
    overflow: hidden;
    background-color: var(--background-color-primary);
    border-radius: 2px;
  }
  .centered {
    text-align: center;
  }

  .google-info {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin-bottom: 16px;
    font-size: 18px;
  }

  .google-info-span {
    font-family: var(--filbert-sans-serif);
    display: block;
    color: var(--title-color-primary);
    overflow: hidden;
    white-space: pre-wrap;
    text-overflow: ellipsis;
    padding: 4px;
  }

  .email {
    display: block;
    font-family: inherit;
    font-size: smaller;
  }

  .choose-username-info {
    display: block;
    font-family: inherit;
    font-weight: 400;
    margin-top: 16px;
  }

  .message-container {
    min-height: 36px;
    margin-bottom: 8px;
    text-align: center;
    font-family: var(--code-font-family);
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .success {
    color: var(--filbert-success);
  }

  .error {
    color: var(--filbert-error);
  }

  section :global(.google-logo-svg) {
    position: absolute;
    margin: 0;
    left: 16px;
    flex-shrink: 0;
    height: 24px;
    width: 24px;
  }

  button {
    display: block;
    width: 100%;
    margin-bottom: 16px;
    background: var(--accent-color-primary);
  }

  a {
      display: block;
    text-align: center;
      margin: 8px;
  }
</style>

<section>
  <form on:submit|preventDefault="{() => isAdminLogin ? doLogin() : doLoginGoogle()}">
    <div class="centered">
      <H1>Sign In</H1>
    </div>
    {#if currentGoogleUser.imageUrl && currentGoogleUser.name && currentGoogleUser.email}
      <div class="google-info">
        <ProfileImg src="{currentGoogleUser.imageUrl}" />
        <span class="google-info-span">{currentGoogleUser.name}</span>
        <span class="google-info-span">
          <span class="email">{currentGoogleUser.email}</span>
        </span>
      </div>
    {/if}
    {#if shouldShowUsernameInput}
      <H2>👋 Welcome!</H2>
      <H3>
        <span class="choose-username-info">
          Just one more step before we continue
        </span>
        <span class="choose-username-info">Choose a filbert username.</span>
      </H3>
      <div class="input-container">
        <label for="username" class:error="{error || usernameIsInvalid}">
          filbert username (lowercase letters a-z and numbers 0-9 only, length 5
          to 42 characters)
        </label>
        <input
          class:error="{error || usernameIsInvalid}"
          bind:value="{usernameValue}"
          bind:this="{usernameInputDomNode}"
          name="username"
          type="text"
          autoComplete="off"
          minLength="5"
          maxLength="42"
        />
      </div>
    {/if}
    {#if isAdminLogin}
      <div class="input-container">
        <label for="username-admin" class:error="{error}">
          filbert username
        </label>
        <input
            class:error="{error}"
            bind:value="{usernameValue}"
            bind:this="{usernameAdminInputDomNode}"
            name="username-admin"
            type="text"
            autoComplete="off"
            minLength="5"
            maxLength="42"
        />
      </div>
      <div class="input-container">
        <label for="password" class:error="{error}">
          password
        </label>
        <input
            class:error="{error || usernameIsInvalid}"
            bind:value="{usernameValue}"
            name="password"
            type="password"
        />
      </div>
      {/if}
    <div class="message-container">
      {#if error}
        <span class="error">
          Try again. {error}{' '}
          <span role="img" aria-label="male police officer">👮</span>
        </span>
      {:else if success}
        <span class="success">{success}</span>
      {/if}
    </div>
    <ButtonSpinner
      id="sign-in-button"
      type="submit"
      primary
      label={signinButtonLabel}
      loading="{signinLoading}"
    >
      {#if !isAdminLogin}
        <GoogleLogoSvg />
      {/if}
    </ButtonSpinner>
    {#if !shouldShowUsernameInput && currentGoogleUser.givenName}
      <button
        class="filbert-nav-button cancel"
        type="button"
        on:click="{doLogout}"
      >
        <span class="button-span">Logout</span>
      </button>
    {:else}
      <a class="filbert-link-alt" href="/">
        <button class="filbert-nav-button cancel">
          <span class="button-span">Cancel</span>
        </button>
      </a>
    {/if}
    {#if isAdminLogin}
      <a href="/signin" class="filbert-link">Google signin</a>
      {:else}
      <a href="/signin?admin" class="filbert-link">admin signin</a>
      {/if}
  </form>
</section>
