// frontend/src/common/components/quote.jsx
import React from 'react';
import styled from 'styled-components';
import { NODE_TYPE_QUOTE } from '../constants';
import {
  A,
  ContentSection,
  ItalicText,
  MiniText,
} from './shared-styled-components';
import { editSectionBorderMixin } from './shared-styled-components-mixins';

const QuoteP = styled.p`
  position: relative;
  margin-bottom: 32px;
  word-break: break-word;
  ${editSectionBorderMixin};
`;

export default React.memo(({ node, isEditing, setEditNodeId }) => {
  console.debug('Quote RENDER', node);

  const id = node.get('id');
  const quote = node.getIn(['meta', 'quote'], '');
  const url = node.getIn(['meta', 'url'], '');
  const author = node.getIn(['meta', 'author'], '');
  const context = node.getIn(['meta', 'context'], '');
  return (
    <ContentSection data-type={NODE_TYPE_QUOTE} name={id}>
      <QuoteP
        isEditMode={setEditNodeId}
        isEditing={isEditing}
        onClick={() => setEditNodeId && setEditNodeId(id)}
      >
        {'💡 '}
        <ItalicText>
          {quote && `"${quote}" `}
          <A target="_blank" href={url}>
            {author && `-${author}`}
          </A>
          <MiniText>{context && ` ${context}`}</MiniText>
        </ItalicText>
      </QuoteP>
    </ContentSection>
  );
});

// web/src/document-components/Quote.svelte
<script>
  export let node;
  export let isEditing = false;
  export let setEditNodeId = undefined;

  import { NODE_TYPE_QUOTE } from '../common/constants';

  $: isEditMode = !!setEditNodeId;

  $: id = node.get('id');
  $: quote = node.getIn(['meta', 'quote'], '');
  $: url = node.getIn(['meta', 'url'], '');
  $: author = node.getIn(['meta', 'author'], '');
  $: context = node.getIn(['meta', 'context'], '');
</script>

<style>
  .wrapper {
    position: relative;
    margin-bottom: 32px;
    word-break: break-word;
    clear: left;
  }
  .drop-cap {
    font-size: 48px;
    line-height: 60px;
    float: left;
    position: relative;
  }
  .quote-context-container {
    display: flex;
    align-items: flex-end;
    flex-direction: column;
  }
  a {
    background-position: 0 calc(1em + 5px);
  }
</style>

<section
  class="filbert-section content-section"
  data-type="{NODE_TYPE_QUOTE}"
  name="{id}"
>
  <div
    class="wrapper"
    class:edit-section-border="{isEditing}"
    class:edit-hover-border="{isEditMode}"
    on:click="{() => setEditNodeId && setEditNodeId(id)}"
  >
    <span class="drop-cap">{'💡'}</span>
    <em class="italic-text">{quote && `"${quote}"`}</em>
    <div class="quote-context-container">
      <a class="filbert-link" target="_blank" href="{url}">
        {author && `-${author}`}
      </a>
      <span class="mini-text">{context && ` ${context}`}</span>
    </div>
  </div>
</section>
