// frontend/src/pages/footer.jsx
import React from 'react';
import styled from 'styled-components';
import GitHubSvg from '../../assets/icons/github-mark.svg';
import InfoSvg from '../../assets/icons/info.svg';
import {
  ALayout,
  LogoLinkStyled,
  SocialIcon,
} from '../common/components/layout-styled-components';
import { codeFontFamily, getVar, grey, lightGrey } from '../variables.css';

const GitHubStyled = styled(GitHubSvg)`
  cursor: pointer;
  ${SocialIcon};
`;
const InfoStyled = styled(InfoSvg)`
  cursor: pointer;
  ${SocialIcon};
`;
const SocialLinksContainer = styled.div`
  display: flex;
  justify-content: center;
`;
const FooterStyled = styled.footer`
  font-family: ${getVar(codeFontFamily)}, monospaced;
  background: ${lightGrey};
  padding: 20px;
  text-align: center;
  color: ${grey};
`;
const Br = styled.div`
  margin: 16px;
`;
const HelpLink = styled(LogoLinkStyled)`
  flex-grow: unset;
`;

export default React.memo(() => (
  <FooterStyled>
    <span role="img" aria-label="truck">
      🚚
    </span>{' '}
    1/4/2020 some-hash-here-34df
    <Br />
    <span role="img" aria-label="baby">
      👶
    </span>{' '}
    1/4/2019
    <SocialLinksContainer>
      <ALayout href="https://github.com/bc-jasond/filbert">
        <GitHubStyled />
      </ALayout>
      <HelpLink to="/help">
        <InfoStyled />
      </HelpLink>
    </SocialLinksContainer>
  </FooterStyled>
));

// sapper/src/layout-components/Footer.svelte
<script>
  import GitHubIcon from '../icons/github-mark.svelte';
  import InfoIcon from '../icons/info.svelte';
</script>

<style>
  footer {
    font-family: var(--code-font-family), monospaced;
    background: var(--filbert-lightGrey);
    padding: 20px;
    text-align: center;
    color: var(--filbert-grey);
  }

  .br {
    margin: 16px;
  }

  .social-links-container {
    display: flex;
    justify-content: center;
    cursor: pointer;
  }

  :global(svg) {
    display: block;
    height: 32px;
    width: 34px;
    margin: 20px 10px 0 10px;
    transition: fill 0.375s;
    fill: var(--filbert-grey);
  }
  :global(svg):hover {
    transition: fill 0.375s;
    fill: var(--filbert-darkGrey);
  }
</style>

<footer>
  <span role="img" aria-label="truck">
      🚚
    </span>{' '}
  1/4/2020 some-hash-here-34df
  <div class="br"></div>
  <span role="img" aria-label="baby">
      👶
    </span>{' '}
  1/4/2019
  <div class="social-links-container">
    <a class="filbert-link-alt" href="https://github.com/bc-jasond/filbert">
      <GitHubIcon/>
    </a>
    <a class="filbert-link-alt" href="/help">
      <InfoIcon/>
    </a>
  </div>
</footer>
